server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:forexdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

fixer:
  api:
    url: https://data.fixer.io/api
    key: YOUR_API_KEY_HERE
